Added nix support
ARTIST-Association/ARTIST pull request #100
Opened 2024-11-27 07:11 UTC by faezs

# Description

Added a nix flake for reproducible builds and easy devShells. I'm sure this is not high on your priority list but happy to fix any issues with the support if they ever come up. 

Fixes # (issue)
N/A

## Type of change
- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-12-02 13:22 UTC, Markus-Goetz requested changes

2024-12-02 13:22 UTC, Markus-Goetz commented on default.nix
> +# An example package with dependencies defined via pyproject.toml
This seems to be a left over generic statement from a template or generator and should be adjusted

2024-12-02 13:22 UTC, Markus-Goetz commented on default.nix
> +    dream2nix.modules.dream2nix.pip
dream2nix is according to their own webpages still heavily in development and not yet ready for productive use. Hence, I would want to avoid using it in ARTIST without further stabilization (c.f. https://github.com/nix-community/dream2nix)

2024-12-02 13:22 UTC, Markus-Goetz commented on flake.lock
> +        "narHash": "sha256-kvjfFW7WAETZlt09AgDn1MrtKzP7t90Vf7vypd3OL1U=",
Since I have never worked with nix(-flake) myself, I do not know what these hashes refer to and whether they are valid or a security concern. How can I verify the integrity to which these resources are pointing?

2024-12-02 13:22 UTC, Markus-Goetz commented on flake.nix
> +  # This example flake.nix is pretty generic and the same for all
This is again a generic header from some template or generator - adjustments for ARTIST would be necessary

2024-12-02 13:22 UTC, Markus-Goetz commented on lock.aarch64-linux.json
> +        "url": "https://files.pythonhosted.org/packages/e0/25/dd5c0f6ac1311e9b40f4af06c78efde0f3b5cbf02502f8ef9501294c425b/MarkupSafe-3.0.2-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.wh
Again, since we have not worked yet with nix, how are these URLs adjusted for the other platforms (e.g. darwin) that have been declared in the other files, while it is here hardcoded to be aarch64?

2024-12-16 08:09 UTC, Markus-Goetz commented
Pull request seems stale @faezs. Are you intending to bring it up-to-date or answer the questions?

2025-01-17 14:14 UTC, kalebphipps commented
Since it has been over a month since our last question and almost two months since the first review requesting changes, I am going to consider this a stale PR and close it without merging!

2025-01-17 14:14 UTC, closed without merging