Features/alignment optimization
ARTIST-Association/ARTIST pull request #96
Opened 2024-11-20 09:28 UTC by MarleneBusch

# Features/alignment optimization

This branch mainly introduces the `AlignmentOptimizer` that can be used to optimize all 28 heliostat kinematic parameters. There are two optimization methods, one uses the motor positions and the other uses raytracing. Optimizing via the motor positions is significantly faster and also more accurate.

This branch also changed other modules.
- The tutorials were not updated in my last feature branch concerning the device, now the default device is also set there.
- The h5 scenarios were updated to also include the power plant position coordinates.
- The actuator used to have a forward method that had no use, i removed it.
- The kinematic module variable names were not consistent, we used to have `actuator_steps`, `motor_steps`, `actuator_pos`, ... all were referring to the same thing that is named `motor_positions` in PAINT, thats why I chose that name for ARTIST as well.
- A new pytest is introduced checking the util method that converts wgs84 to enu.
- In the heliostat module, the `get_surface_points_and_surface_normals` method was moved from the alignement method to the init. This way it is only called once and not with each new alignment.
- Inplace operations in the kinematic and raytracing were removed to make the modules differentiable.
- A `PAINT_to_surface` converter was added to use PAINT data and create scenarios from it.
- Overall I also found pieces of code that used the math library, I changed that to torch.
 

Fixes #91 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-12-03 14:56 UTC, mcw92 commented on artist/field/actuator_linear.py
> +        Calculate phi (angle) from the motor position.
Can you maybe explain what phi exactly is, i.e., angle between what?
If this is only a "private" helper function, should we maybe rename it to `_steps_to_phi()`?

2024-12-03 14:59 UTC, mcw92 commented on artist/field/actuator_linear.py
> +        stroke_length = motor_position / self.increment + self.initial_stroke_length
Can you add explaining comments what these quantities mean? It really looks like you now understand what's going on in ARTIST in detail (we do not anymore 😬 ) so it would be great if you could try to make the code more self-explaining by adding more comments.

2024-12-03 15:08 UTC, mcw92 commented on artist/field/actuator_linear.py
> -    def forward(
According to the [PyTorch documentation](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.forward), the `forward` method of each subclass of `torch.nn.Module` should always be overridden, as it defines the computation performed at every call. However, we should definitely think about what should actually happen in `forward` as this is called upon calling the module instance (including hooks).

2024-12-03 15:12 UTC, mcw92 commented on artist/field/heliostat.py
> +        return orientation
```suggestion
        return self.kinematic.motor_positions_to_orientation(
            motor_positions, torch.device(device)
        )
```

2024-12-03 15:16 UTC, mcw92 commented on artist/field/kinematic_rigid_body.py
>          ), "The rigid body kinematic requires exactly two actuators, please check the configuration!"
```suggestion
        if len(self.actuators.actuator_list) != 2:
            raise ValueError(f"The rigid body kinematic requires exactly two actuators but {len(self.actuators.actuator_list)} were specified, please check the configuration!")
```
I'd suggest to replace all asserts with proper exceptions as it is in principle possible to turn off asserts. However, this would also require expanding the tests to also cover each exception.

2024-12-03 15:22 UTC, mcw92 commented on artist/field/kinematic_rigid_body.py
> +                    a * -desired_concentrator_normal[2:3]
Just asking out of curiosity: Why do the slices change, i.e., why do we now only have one dimension? Is this because we now have only one "angle" compared to multiple "angles" before (see variable name)?
Can we also put only 2 instead of 2:3? This should be the same, right?

2024-12-03 15:27 UTC, mcw92 commented on artist/field/kinematic_rigid_body.py
> +        joint_1_rotation = (
Can you explain the order of the rotation and translation operations performed here?

2024-12-03 15:31 UTC, mcw92 commented on artist/scenario.py
> +        The position of the power plant in lat, lon, alt.
```suggestion
        The position of the power plant as latitude, longitude, altitude.
```

2024-12-03 15:37 UTC, MarleneBusch commented on artist/field/actuator_linear.py
> +        Calculate phi (angle) from the motor position.
I dont know much more about phi.
But since phi_0  is the "minimal angle, when in minimum motorposition" , I would assume phi is the angle of the joint?

2024-12-03 15:39 UTC, mcw92 commented on artist/util/alignment_optimizer.py
> +    Implements an alignment optimizer to find optimal kinematic parameters.
```suggestion
    Alignment optimizer to find optimal kinematic parameters.
```

2024-12-03 15:40 UTC, MarleneBusch commented on artist/field/actuator_linear.py
> -    def forward(
ActuatorLinear is not actually a direct subclass of `torch.nn.Module`  but a subclass of `Actuator`. 
`Actuator` is indeed a subclass of `torch.nn.Module`.

However this problem then exists in multiple classes in actuator/field/

2024-12-03 15:41 UTC, mcw92 commented on artist/util/alignment_optimizer.py
> +        The optimizer.
Please be a bit more specific about the scenario being optimized, i.e., explain parameters in more detail.

2024-12-03 15:42 UTC, mcw92 commented on artist/util/alignment_optimizer.py
> +        Optimize the kinematic parameters using raytracing (slower).
I am not sure whether private methods should appear in a class docstring. I think it's not common practice to do so.

2024-12-03 15:43 UTC, mcw92 commented on artist/util/alignment_optimizer.py
> +        These parameters can include the 18 kinematic deviations parameters as well as 5 actuator
```suggestion
        These parameters can include the 18 kinematic deviations parameters as well as five actuator
```

2024-12-03 15:44 UTC, mcw92 commented on artist/util/alignment_optimizer.py
> +            The optimzer tolerance.
```suggestion
            The optimizer tolerance.
```

2024-12-03 15:44 UTC, mcw92 commented on artist/util/alignment_optimizer.py
> +        incident_ray_direction: torch.Tensor
```suggestion
        center_calibration_image : torch.Tensor
            The center of the calibration flux density.
        incident_ray_direction : torch.Tensor
```

2024-12-03 15:45 UTC, mcw92 commented on artist/util/alignment_optimizer.py
> +        device: Union[torch.device, str] = "cuda"
```suggestion
        motor_positions : Optional[torch.Tensor]
            The motor positions specified in the calibration (default is None).
        device : Union[torch.device, str] = "cuda"
```

2024-12-03 15:48 UTC, mcw92 commented on artist/util/alignment_optimizer.py
> +                    device=device,
Can you use keyworded arguments consistently?

2024-12-03 15:49 UTC, mcw92 commented on artist/util/alignment_optimizer.py
> +                    tolerance,
Consistent use of keyworded arguments (see above)

2024-12-03 15:51 UTC, mcw92 commented on artist/util/alignment_optimizer.py
> +        and incident ray direction from a specific calibration and using the scence's geometry.
```suggestion
        and incident ray direction from a specific calibration and using the scene's geometry.
```

2024-12-03 15:52 UTC, mcw92 commented on artist/util/alignment_optimizer.py
> +        motor_positions: torch.Tensor
```suggestion
        center_calibration_image : torch.Tensor
            The center of the calibration flux density.
        incident_ray_direction : torch.Tensor
            The incident ray direction specified in the calibration.
        motor_positions : torch.Tensor
```

2024-12-03 15:55 UTC, mcw92 commented on artist/util/alignment_optimizer.py
> +        # can be removed if we decide to only return the optimized paramters.
This sounds like a hidden to do in the code. Which of these options do you prefer? Currently, both the list of optimized parameters and the aligned scenario are returned, right? What would be reason to not return the scenario?

2024-12-03 15:58 UTC, mcw92 commented on artist/util/alignment_optimizer.py
> +        incident_ray_direction: torch.Tensor
```suggestion
        center_calibration_image : torch.Tensor
            The center of the calibration flux density.
        incident_ray_direction : torch.Tensor
```

2024-12-03 16:00 UTC, mcw92 commented on artist/util/alignment_optimizer.py
> +            # Align heliostat
```suggestion
            # Align heliostat.
```

2024-12-03 16:00 UTC, mcw92 commented on artist/util/alignment_optimizer.py
> +            # Create raytracer
```suggestion
            # Create raytracer.
```

2024-12-03 16:01 UTC, mcw92 commented on artist/util/alignment_optimizer.py
> +            center = utils.get_center_of_mass(
PyCharm gives a warning that `plane_e` and `plane_u` are expceted type `torch.Tensor` but get `float`. Maybe you can double-check this :).

2024-12-03 16:03 UTC, mcw92 commented on artist/util/alignment_optimizer.py
> +                torch.flip(final_bitmap.T, dims=(0, 1)),
Why do we need to flip the bitmap here? This is related to issue #97 and we should definitely find out why that is.

2024-12-03 16:05 UTC, mcw92 commented on artist/util/alignment_optimizer.py
> +            if epoch in [max_epoch // 4, 2 * (max_epoch // 4), 3 * (max_epoch // 4)]:
What is this condition? You only want to log specific epochs? I find it a bit weird to fix the logging interval if the number of epochs itself can in principle vary.

2024-12-04 09:26 UTC, MarleneBusch commented on artist/field/actuator_linear.py
> +        stroke_length = motor_position / self.increment + self.initial_stroke_length
I added more context to the docstrings.

Also, I renamed radius to pivot_radius and phi_0 to initial_angle, as recommended by Max.

2024-12-04 09:35 UTC, MarleneBusch commented on artist/field/heliostat.py
> +    surface_normals
done

2024-12-04 09:35 UTC, MarleneBusch commented on artist/field/heliostat.py
> +        return orientation
done

2024-12-04 09:42 UTC, MarleneBusch commented on artist/field/kinematic_rigid_body.py
>          ), "The rigid body kinematic requires exactly two actuators, please check the configuration!"
Okay, I changed this part of the code to follow your suggestion.
I also opened an issue to fix all other parts of artist where we are using assert statements. 

Maybe this does not need to be solved right now in this branch?

2024-12-04 09:55 UTC, MarleneBusch commented on artist/field/kinematic_rigid_body.py
> +                    a * -desired_concentrator_normal[2:3]
Yes, originally Moritz Code worked slightly different and in his code it was possible to calculate multiple orientation matrices at once.
The way we refactored ARTIST doesn't allow this - i think. This method to calculate the orientation is bound to one instance of the kinematic_rigid_body and a single kinematic_rigid_body instance belongs to a single heliostat. A single heliostat can only align itself according to one orientation matrix at once, this is why we only need to calculate one orientation matrix at once. We might have to rethink this for the multi heliostat support anyways but in this current branch it doesnt make sense to name the variables in the plural and expect multiple angles where there will only be one. That is why i changed it to singular, removed the possibilities for lists and had to adapt the slicing.

Do you want me to change it back or should we accept it like i suggested in this branch and change it to something smart once we agreed on a structure for multiple heliostats?

2024-12-04 10:03 UTC, MarleneBusch commented on artist/field/kinematic_rigid_body.py
> +                    a * -desired_concentrator_normal[2:3]
Also we cannot just put 2 instead of 2:3. `desired_concentrator_normal` is 4 dimensional. 

Example:
`desired_concentrator_normal` : `tensor([ 0.0000, -0.7071,  0.7071,  0.0000])`
`desired_concentrator_normal[2:]`  : `tensor([0.7071, 0.0000])`
`desired_concentrator_normal[2:3]` :  `tensor([0.7071])`

2024-12-04 10:42 UTC, MarleneBusch commented on artist/field/kinematic_rigid_body.py
> +        ).squeeze()
1. orientation = self.incident_ray_direction_to_orientation(incident_ray_direction, device=device) I removed the squeeze here, because it doesnt do anything at all, i guess its left over from previous work.
2. aligned_surface_points = (orientation @ surface_points.unsqueeze(-1)).squeeze(-1) This statement really needs the squeeze and unsqueeze operations because of differing dimensions. orientation.shape = (4, 4), surface_points.shape = (4, 10000, 4) therfore its not possible to just use @ and multiply, an extra dimension has to be introduced and then removed.
3. same for: aligned_surface_normals = (orientation @ surface_normals.unsqueeze(-1)).squeeze(-1)

Instead of squeezing and unsqueezing we can also do:
        aligned_surface_points = surface_points @ orientation.T
        aligned_surface_normals = surface_normals @ orientation.T
The result is the same, I dont know which is better for the runtime

2024-12-04 10:43 UTC, MarleneBusch commented on artist/field/kinematic_rigid_body.py
> +        ), "The rigid body kinematic requires exactly two actuators, please check the configuration!"
done

2024-12-04 10:48 UTC, MarleneBusch commented on artist/field/kinematic_rigid_body.py
> +        joint_1_rotation = (
No this would be something Moritz (or maybe Max) would have to do. I did not create the logic behind the kinematic_rigid_body and dont think it would be efficient if i try to really figure it out.

2024-12-04 10:59 UTC, MarleneBusch commented on artist/scenario.py
> +        The position of the power plant in lat, lon, alt.
done

2024-12-04 10:59 UTC, MarleneBusch commented on artist/scenario.py
> +            The position of the power plant in lat, lon, alt.
done

2024-12-04 11:01 UTC, MarleneBusch commented on artist/util/alignment_optimizer.py
> +    Implements an alignment optimizer to find optimal kinematic parameters.
done

2024-12-04 11:03 UTC, MarleneBusch commented on artist/util/alignment_optimizer.py
> +        The optimizer.
okay

2024-12-04 11:04 UTC, MarleneBusch commented on artist/util/alignment_optimizer.py
> +        Optimize the kinematic parameters using raytracing (slower).
okay, I don't know much about that but i removed them

2024-12-04 11:05 UTC, MarleneBusch commented on artist/util/alignment_optimizer.py
> +        These parameters can include the 18 kinematic deviations parameters as well as 5 actuator
okay

2024-12-04 11:05 UTC, MarleneBusch commented on artist/util/alignment_optimizer.py
> +            The optimzer tolerance.
yes

2024-12-04 11:06 UTC, MarleneBusch commented on artist/util/alignment_optimizer.py
> +        incident_ray_direction: torch.Tensor
done

2024-12-04 11:06 UTC, MarleneBusch commented on artist/util/alignment_optimizer.py
> +        device: Union[torch.device, str] = "cuda"
done

2024-12-04 11:07 UTC, MarleneBusch commented on artist/util/alignment_optimizer.py
> +        log.info("Start alignment optimization")
done

2024-12-04 11:08 UTC, MarleneBusch commented on artist/util/alignment_optimizer.py
> +                    device=device,
done

2024-12-04 11:08 UTC, MarleneBusch commented on artist/util/alignment_optimizer.py
> +                    tolerance,
done

2024-12-04 11:08 UTC, MarleneBusch commented on artist/util/alignment_optimizer.py
> +        and incident ray direction from a specific calibration and using the scence's geometry.
done

2024-12-04 11:08 UTC, MarleneBusch commented on artist/util/alignment_optimizer.py
> +        motor_positions: torch.Tensor
done

2024-12-04 11:10 UTC, MarleneBusch commented on artist/util/alignment_optimizer.py
> +        # can be removed if we decide to only return the optimized paramters.
I thpught about it and decided it always makes sense to return the scenario

2024-12-04 11:11 UTC, MarleneBusch commented on artist/util/alignment_optimizer.py
> +        incident_ray_direction: torch.Tensor
done

2024-12-04 11:11 UTC, MarleneBusch commented on artist/util/alignment_optimizer.py
> +            # Create raytracer
done

2024-12-04 11:13 UTC, MarleneBusch commented on artist/util/alignment_optimizer.py
> +            center = utils.get_center_of_mass(
Yes they are floats, i corrected this.

2024-12-04 11:14 UTC, MarleneBusch commented on artist/util/alignment_optimizer.py
> +                torch.flip(final_bitmap.T, dims=(0, 1)),
Yes I agree, but i cannot do that on my own.

2024-12-04 11:18 UTC, MarleneBusch commented on artist/util/alignment_optimizer.py
> +            if epoch in [max_epoch // 4, 2 * (max_epoch // 4), 3 * (max_epoch // 4)]:
mhhh yes it is weird.
My idea was, that i always want to log 3 epochs, no matter how many max_epochs the user sets.
If the user decides on max_epoch=30, but the AlignmentOptimizer is set to only log every 50th epoch, the user will not get any log statements because 30<50. 

I can change it if you want.

2024-12-05 08:04 UTC, MarleneBusch commented on artist/field/kinematic_rigid_body.py
>          ), "The rigid body kinematic requires exactly two actuators, please check the configuration!"
I pushed another version where i exchanged all assterts to ValueErrors except in the tests. I did not yet create all test cases.

2024-12-05 08:06 UTC, MarleneBusch commented on artist/field/kinematic_rigid_body.py
>          ), "The rigid body kinematic requires exactly two actuators, please check the configuration!"
This breaks some tests. I will fix it

2024-12-05 10:00 UTC, MarleneBusch commented on artist/field/kinematic_rigid_body.py
>          ), "The rigid body kinematic requires exactly two actuators, please check the configuration!"
The pytests work again now. However the code coverage was lowered due to the if statements, This makes the git checks fail. I dont know what to do about that.

2024-12-06 08:36 UTC, mcw92 commented on artist/field/actuator_linear.py
> -    def forward(
We have checked again with @Markus-Goetz and there should definitely be `forward()` methods for all child classes of `torch.nn.Module`. However, this means we should carefully think about what we expect to happen if we call an instance of each of the above mentioned classes as this would automatically call the corresponding `forward` method (including hooks).
For now, you could implement those `forward` methods where you already know what should happen and make an issue for those where you don't. Ideally, also tag @Filos1992 because we definitely would need his opinion here. For thos classes, where it is unclear and we do not know yet what we want to happen, you could implement "stubs", like:
```
def forward(self) -> None:
    raise NotImplementedError
```
Or would this break already working functionality?

2024-12-06 08:37 UTC, mcw92 commented on artist/field/heliostat.py
> +                raise ValueError(
Could you include a test function checking that this `ValueError` appears as expected (so that the codecov warning goes away)?

2024-12-06 08:40 UTC, mcw92 commented on artist/field/heliostat.py
> +                raise ValueError(
See above. There is specific functionality in `pytest` to do that, like:
```
with pytest.raises(ValueError): 
    # Call test function
```

2024-12-06 08:41 UTC, mcw92 commented on artist/field/heliostat.py
> +                raise ValueError(
See above, make sure line is covered by tests :).

2024-12-06 08:42 UTC, mcw92 commented on artist/field/heliostat.py
> +            raise ValueError("Heliostat has not yet been aligned.")
See above.

2024-12-06 08:50 UTC, mcw92 commented on artist/field/kinematic_rigid_body.py
> +                    a * -desired_concentrator_normal[2:3]
Regarding your first comment: Okay, understood. I would suggest to not change it back and leave it the way it is right now.
Regarding your second comment:
What about just:
`desired_concentrator_normal[2] : tensor(0.7071)`
The resulting shape is different from `2:3` (no "[]"), not sure it would work in the code. We can also just leave it the way it is. We were just wondering why that is.

2024-12-06 09:02 UTC, mcw92 commented on artist/util/alignment_optimizer.py
> +        log.info("Create alignment optimizer")
```suggestion
        log.info("Create alignment optimizer.")
```

2024-12-06 09:04 UTC, mcw92 commented on artist/util/alignment_optimizer.py
> +            The motor positions specified in the calibration (default is None).
```suggestion
            The motor positions specified in the calibration (default is ``None``).
```

2024-12-06 09:14 UTC, mcw92 commented on artist/util/alignment_optimizer.py
> +                torch.flip(final_bitmap.T, dims=(0, 1)),
We set the urgency of the corresponding issue to "high" (there are now issue labels for this). Could you please tag all persons who might be helpful in resolving this? Maybe we should set up a joint meeting to discuss this with everyone.

2024-12-06 09:17 UTC, MarleneBusch commented on artist/field/actuator_linear.py
> -    def forward(
I understand that we need to implement them if torch requires us to do so.
I dont understand how i can figure out what the individual forward methods should do. Therefore i would implement your suggestion
 ```
def forward(self) -> None:
    raise NotImplementedError
```
everywhere.
I cannot recall a single part of the artist code where we just call an instance of such a class.
That is why I think it would break working functionality

2024-12-06 09:23 UTC, mcw92 commented on artist/util/alignment_optimizer.py
> +            if epoch in [max_epoch // 4, 2 * (max_epoch // 4), 3 * (max_epoch // 4)]:
Could we introduce a parameter `num_log` to specify how many log messages a user wants?

```
log_step = max_epoch // num_log  # Calculate logging step.
while loss > tolerance and epoch <= max_epoch:
    ...
    if epoch % log_step == 0:
        log.info(...) 
```

2024-12-06 09:26 UTC, mcw92 commented on artist/util/config_dictionary.py
> +WGS84_E2 = (WGS84_A**2 - WGS84_B**2) / WGS84_A**2  # Eccentricity squared
Can you maybe put this as a (global) variable or even just defined constant into the file or function where this is actually used? This only appears once in `convert_wgs84_coordinates_to_local_enu()`.

2024-12-06 09:27 UTC, mcw92 commented on artist/util/configuration_classes.py
> +        The position of the power plant in lat, lon, alt.
```suggestion
        The position of the power plant as latitude, longitude, altitude.
```

2024-12-06 09:28 UTC, mcw92 commented on artist/util/configuration_classes.py
> +    create_power_plant_dict
```suggestion
    create_power_plant_dict()
```

2024-12-06 09:28 UTC, mcw92 commented on artist/util/configuration_classes.py
> +            The position of the power plant in lat, lon, alt.
```suggestion
            The position of the power plant as latitude, longitude, altitude.
```

2024-12-06 09:29 UTC, mcw92 commented on artist/util/configuration_classes.py
> +        Dict[str, Any]
```suggestion
        dict[str, Any]
```

2024-12-06 09:51 UTC, mcw92 commented on artist/util/utils.py
> +# from artist.scenario import Scenario
Can this be removed?

2024-12-06 09:52 UTC, mcw92 commented on artist/util/utils.py
> +        Specifies if input is given in degrees or radians.
```suggestion
        Whether input is given in degrees or radians.
```

2024-12-06 09:53 UTC, mcw92 commented on artist/util/utils.py
> +    srange: float = 1.0,
Can we rename this to `slant_range`?

2024-12-06 09:55 UTC, mcw92 commented on artist/util/utils.py
> +        The coordinates in lat, lon, alt that are to be transformed.
```suggestion
        The coordinates in latitude, longitude, altitude that are to be transformed.
```

2024-12-06 09:56 UTC, mcw92 commented on artist/util/utils.py
> +    # Convert latitude and longitude to radians
```suggestion
    # Convert latitude and longitude to radians.
```

2024-12-06 09:56 UTC, mcw92 commented on artist/util/utils.py
> +    # Calculate meridional radius of curvature for the first latitude
```suggestion
    # Calculate meridional radius of curvature for the first latitude.
```

2024-12-06 09:56 UTC, mcw92 commented on artist/util/utils.py
> +    # Calculate transverse radius of curvature for the first latitude
```suggestion
    # Calculate transverse radius of curvature for the first latitude.
```

2024-12-06 09:56 UTC, mcw92 commented on artist/util/utils.py
> +    # Calculate delta latitude and delta longitude in radians
```suggestion
    # Calculate delta latitude and delta longitude in radians.
```

2024-12-06 09:57 UTC, mcw92 commented on artist/util/utils.py
> +    # Calculate north and east offsets in meters
```suggestion
    # Calculate north and east offsets in meters.
```

2024-12-06 10:00 UTC, mcw92 commented on artist/util/utils.py
> +    torch.Tensor
```suggestion
    Returns
    -------
    torch.Tensor
```

2024-12-06 10:00 UTC, mcw92 commented on artist/util/utils.py
> +    # Calculate center of mass of the bitmap
```suggestion
    # Calculate center of mass of the bitmap.
```

2024-12-06 10:02 UTC, mcw92 commented on artist/util/utils.py
> +    center_of_mass_bitmap = torch.stack([center_of_mass_x, center_of_mass_y], dim=-1)
What exactly are x and y? Are they already somehow related to the ENU coordinate system that we use in ARTIST?

2024-12-06 10:02 UTC, mcw92 commented on artist/util/utils.py
> +    # Construct the coordinates relative to target center
```suggestion
    # Construct the coordinates relative to target center.
```

2024-12-06 10:03 UTC, mcw92 commented on artist/util/utils.py
> +# The type hint for scenario should be Scenario, but Scenario cannot be imported due to circular imports.
```suggestion
```

2024-12-06 10:04 UTC, mcw92 commented on artist/util/utils.py
> +    scenario: Any,
```suggestion
    scenario: "Scenario",
```

2024-12-06 10:06 UTC, mcw92 commented on artist/util/utils.py
> +from typing import Any, Union
```suggestion
from typing import Any, TYPE_CHECKING, Union

if TYPE_CHECKING:
    from artist.scenario import Scenario
```

2024-12-06 10:06 UTC, mcw92 commented on artist/util/utils.py
> +# from artist.scenario import Scenario
```suggestion
```
This can be removed if we do the type hint as stated above.

2024-12-06 10:12 UTC, mcw92 commented on artist/util/utils.py
> +# The type hint for scenario should be Scenario, but Scenario cannot be imported due to circular imports.
```suggestion
```

2024-12-06 10:13 UTC, mcw92 commented on artist/util/utils.py
> +    scenario: Any,
```suggestion
    scenario: "Scenario",
```

2024-12-06 10:14 UTC, mcw92 commented on artist/util/utils.py
> +    scenario : Scenario
Please pass the power plant position only instead of the whole Scenario since this is the only attribute used.

2024-12-06 10:24 UTC, mcw92 commented on tests/data/scenario_generators/generate_scenario_for_test_alignment_optimizer.py
> +with open(calibration_file, "r") as file:
Two general comments for this script:

1.) As far as we can tell, you are loading `PAINT` data here. Since this will probably happen more often, it would be good to create a file `paint_loader.py` or similar and write functions that are designed to load different element, e.g. `load_calibration_properties()` based on a file path. Therefore it would be good if you could adjust all of the loads below to be in external functions.

2.) All the strings used in the keys should be mappings. These mappings are in `PAINT` already - for now I would suggest copying the `paint_mappings` file into ARTIST and importing from there -- in the long term we can consider if making `PAINT` a dependency in `ARTIST` makes sense.

2024-12-06 11:20 UTC, MarleneBusch commented on artist/util/config_dictionary.py
> +WGS84_E2 = (WGS84_A**2 - WGS84_B**2) / WGS84_A**2  # Eccentricity squared
done

2024-12-06 11:21 UTC, MarleneBusch commented on artist/util/configuration_classes.py
> +        The position of the power plant in lat, lon, alt.
done

2024-12-06 11:21 UTC, MarleneBusch commented on artist/util/configuration_classes.py
> +    create_power_plant_dict
done

2024-12-06 11:21 UTC, MarleneBusch commented on artist/util/configuration_classes.py
> +            The position of the power plant in lat, lon, alt.
done

2024-12-06 11:22 UTC, MarleneBusch commented on artist/util/configuration_classes.py
> +        Dict[str, Any]
done

2024-12-06 11:48 UTC, mcw92 commented on artist/field/actuator_linear.py
> -    def forward(
I assume you mean would *not* break working functionality in the last sentencen, right? If that's the case, we just leave it like it is. Can you create an issue to document the need to discuss this further?

2024-12-06 11:49 UTC, MarleneBusch commented on artist/util/stral_to_surface_converter.py
>                  number_of_points = facet_header_data[10]
done.

While looking at the the binary_extractor in PAINT i noticed something that might be wrong there. 

I think - but dont fully know what else you do in PAINT - that in lines 143-150 confuse e and n for the canting vectors. The canting vectors are not really important and are currently not used in artist, therefore nobody or no test checks if these values make sense.

2024-12-06 11:50 UTC, MarleneBusch commented on artist/util/stral_to_surface_converter.py
>                  number_of_points = facet_header_data[10]
i opened a paint issue for you

2024-12-06 11:51 UTC, MarleneBusch commented on artist/util/utils.py
> +        Specifies if input is given in degrees or radians.
done

2024-12-06 11:52 UTC, mcw92 commented on artist/field/kinematic_rigid_body.py
> +        # aligned_surface_normals = surface_normals @ orientation.T
What is this?

2024-12-06 11:52 UTC, MarleneBusch commented on artist/util/utils.py
> +    srange: float = 1.0,
done

2024-12-06 11:53 UTC, MarleneBusch commented on artist/util/utils.py
> +        The coordinates in lat, lon, alt that are to be transformed.
done

2024-12-06 11:54 UTC, MarleneBusch commented on artist/util/utils.py
> +    # Convert latitude and longitude to radians
done

2024-12-06 11:54 UTC, MarleneBusch commented on artist/util/utils.py
> +    # Calculate meridional radius of curvature for the first latitude
done

2024-12-06 11:54 UTC, MarleneBusch commented on artist/util/utils.py
> +    # Calculate transverse radius of curvature for the first latitude
done

2024-12-06 11:54 UTC, MarleneBusch commented on artist/util/utils.py
> +    # Calculate delta latitude and delta longitude in radians
done

2024-12-06 11:54 UTC, MarleneBusch commented on artist/util/utils.py
> +    # Calculate north and east offsets in meters
done

2024-12-06 11:55 UTC, MarleneBusch commented on artist/util/utils.py
> +    torch.Tensor
done

2024-12-06 11:55 UTC, MarleneBusch commented on artist/util/utils.py
> +    # Calculate center of mass of the bitmap
done

2024-12-06 11:57 UTC, MarleneBusch commented on artist/util/utils.py
> +    center_of_mass_bitmap = torch.stack([center_of_mass_x, center_of_mass_y], dim=-1)
i changed them to e and u for east and up

2024-12-06 11:57 UTC, MarleneBusch commented on artist/util/utils.py
> +    # Construct the coordinates relative to target center
done

2024-12-06 11:57 UTC, MarleneBusch commented on artist/util/utils.py
> +# The type hint for scenario should be Scenario, but Scenario cannot be imported due to circular imports.
done

2024-12-06 12:02 UTC, mcw92 commented on artist/util/paint_to_surface_converter.py
> +    def normalize_evaluation_points_for_nurbs(points: torch.Tensor) -> torch.Tensor:
Can we rename `points` to `surface_points`?

2024-12-06 12:07 UTC, MarleneBusch commented on artist/util/utils.py
> +    scenario: Any,
done

2024-12-06 12:08 UTC, mcw92 commented on artist/util/paint_to_surface_converter.py
> +    def fit_nurbs_surface(
This function and the `normalize_evaluation_points_for_nurbs` are identical to the functions with the same names in the `StralToSurfaceConverter`. To avoid code duplicates, we suggest to move them to `util.nurbs`.

Alternatively (even better), we could create a `SurfaceConverter` parent class in `util/surface_converter.py`, which defines this parent class including shared methods. The derived child classes (if necessary at all) could then inherit from this class and overwrite or add methods as needed. However, it may be possible to simply create a surface converter class with common attributes and have different methods defining the conversion to be performed.

2024-12-06 12:09 UTC, MarleneBusch commented on artist/util/utils.py
> +# from artist.scenario import Scenario
done

2024-12-06 12:09 UTC, MarleneBusch commented on artist/util/utils.py
> +# The type hint for scenario should be Scenario, but Scenario cannot be imported due to circular imports.
done

2024-12-06 12:10 UTC, MarleneBusch commented on artist/util/utils.py
> +    scenario: Any,
done

2024-12-06 12:11 UTC, mcw92 commented on artist/util/paint_to_surface_converter.py
> +            The conversion method used to learn the NURBS.
Could you list possible options for this parameter in the docstring?

2024-12-06 12:13 UTC, mcw92 commented on artist/util/paint_to_surface_converter.py
> +        Parameters
In the long term, we could consider moving the NURBS "base" parameters as attributes to the SurfaceConverter and only pass conversion-dependent parameters here.

2024-12-06 12:14 UTC, MarleneBusch commented on artist/util/utils.py
> +from typing import Any, Union
done

2024-12-06 12:14 UTC, MarleneBusch commented on artist/util/utils.py
> +    scenario : Scenario
done

2024-12-06 12:15 UTC, MarleneBusch commented on artist/field/kinematic_rigid_body.py
> +        # aligned_surface_normals = surface_normals @ orientation.T
This is the solution to another unresolved conversation from the beginning of this pull request. See above.
Originally you asked why we need to squeeze and unsqueeze. Its because of dimensions. If you dont like squeeze and unsqueeze we can choose this commented option that doesnt use squeeze and unsqueeze.

2024-12-06 12:16 UTC, mcw92 commented on artist/util/paint_to_surface_converter.py
> +        with open(self.heliostat_file_path, "r") as file:
Here you are again loading PAINT data. Please move this into a function as mentioned above in the `paint_loader.py` and use mappings instead of strings.

2024-12-06 12:18 UTC, mcw92 commented on artist/util/paint_to_surface_converter.py
> +        # How to deal with different amount of points on different facets?
This To Do should be solved before mergin. As mentioned in the STRAL converter, for now, just take the first N points, where N is the number of points on the facet with the smallest number of points.

2024-12-06 12:20 UTC, mcw92 commented on artist/util/paint_to_surface_converter.py
> +        # Select only selected number of points to reduce compute.
Once the surface points, surface normals, and facets etc. have been loaded from PAINT or STRAL, this post-processing is identical and should therefore also be moved into a separate function that both converters call.

2024-12-06 12:21 UTC, mcw92 commented on artist/util/paint_to_surface_converter.py
> +        log.info("Surface configuration based on STRAL data complete!")
Please also adapt the log messages accordingly.

2024-12-06 12:23 UTC, mcw92 commented on artist/util/paint_to_surface_converter.py
> +            for f in range(number_of_facets):
In this loop, you could probably extract the facet with the smallest number of points.

2024-12-06 12:27 UTC, mcw92 commented on artist/util/paint_to_surface_converter.py
> +            for f in range(number_of_facets):
You could also directly extract the surface points / surface normals with list comprehension into "number of facets" torch tensors in the list. Then, you could find the one with the least number of points and adapt the others accordingly.

2024-12-06 12:35 UTC, mcw92 commented on tests/data/scenario_generators/generate_scenario_for_test_alignment_optimizer.py
> +    plane_e = (
This looks like a utils function for creating a plane based on corner points.

2024-12-06 12:38 UTC, mcw92 commented on tests/data/scenario_generators/generate_scenario_for_test_alignment_optimizer.py
> +    concentrator_translation_u=torch.tensor(-0.4045, device=device),
These parameters should also now be in PAINT.

2024-12-06 12:47 UTC, mcw92 commented on tests/field/test_kinematic_with_measured_parameters.py
> +    ].initial_angle = torch.tensor(0.959931, device=device)
Shouldn't all these parameters already be set in the scenario definition?

2024-12-06 12:48 UTC, mcw92 commented on tests/field/test_kinematic_with_measured_parameters.py
> +    Test the kinematic with measured parameters.
What is the purpose of this test? It appears to call functions that are already covered in other tests with the only difference being that very specific parameters are set. Shouldn't we have unit tests that already guarantee that these parameters work as desired?

2024-12-06 12:50 UTC, mcw92 commented on tests/field/test_kinematic_with_measured_parameters.py
> +    assert final_bitmap.sum() != 0
Can you explain this final assert? It looks like we do not check whether the result is really correct but only if "something" happens.

2024-12-06 12:51 UTC, MarleneBusch commented on tests/data/scenario_generators/generate_scenario_for_test_alignment_optimizer.py
> +    concentrator_translation_u=torch.tensor(-0.4045, device=device),
Not yet in their final form...

2024-12-06 12:51 UTC, MarleneBusch commented on tests/data/scenario_generators/generate_scenario_for_test_alignment_optimizer.py
> +)
not yet...

2024-12-06 12:53 UTC, MarleneBusch commented on tests/field/test_kinematic_with_measured_parameters.py
> +    ].initial_angle = torch.tensor(0.959931, device=device)
Max wanted it exactly like this

2024-12-06 12:53 UTC, MarleneBusch commented on tests/field/test_kinematic_with_measured_parameters.py
> +    Test the kinematic with measured parameters.
We do.

2024-12-06 12:53 UTC, MarleneBusch commented on tests/field/test_kinematic_with_measured_parameters.py
> +    assert final_bitmap.sum() != 0
yes

2024-12-06 12:55 UTC, mcw92 commented on tests/util/test_alignment_optimizer_methods.py
> +    # Load the calibration data
```suggestion
    # Load the calibration data.
```

2024-12-06 12:56 UTC, mcw92 commented on tests/util/test_alignment_optimizer_methods.py
> +def test_alignment_optimizer_methods(
This looks like a good integration test but would it be also possible to test the individual parts of the optimizer with unit tests?

2024-12-06 12:56 UTC, MarleneBusch commented on tests/data/scenario_generators/generate_scenario_for_test_integration_stral.py
> +file_path = file_path = pathlib.Path(ARTIST_ROOT) / "tests/data/test_scenario_stral"
done

2024-12-06 12:57 UTC, mcw92 commented on tests/util/test_alignment_optimizer_methods.py
> +    # Create alignment optimizer
```suggestion
    # Create alignment optimizer.
```

2024-12-06 12:59 UTC, mcw92 commented on tests/util/test_alignment_optimizer_methods.py
> +def test_alignment_optimizer_methods(
I feel like this test only helps to identify problems occurring in the future and does not clearly show that the currently implemented logic of the optimizer works properly.

2024-12-06 13:00 UTC, mcw92 commented on tests/util/test_alignment_optimizer_methods.py
> +    if optimizer_method == "use_raytracing":
"use_raytracing" should also be a mapping. In general, concrete strings should be avoided.

2024-12-06 13:04 UTC, mcw92 commented on tests/util/test_wgs84_to_enu.py
> +        # Coordinates of Jülich power plant and multifocustower
```suggestion
        # Coordinates of Jülich power plant and multi-focus tower
```

2024-12-06 13:10 UTC, mcw92 commented on tutorials/alignment_optimization_tutorial.py
> +# Set up logger
```suggestion
# Set up logger.
```

2024-12-06 13:11 UTC, mcw92 commented on tutorials/alignment_optimization_tutorial.py
> +# Set the device
```suggestion
# Set the device.
```

2024-12-06 13:11 UTC, mcw92 commented on tutorials/alignment_optimization_tutorial.py
> +# Choose calibration data
```suggestion
# Choose calibration data.
```

2024-12-06 13:11 UTC, mcw92 commented on tutorials/alignment_optimization_tutorial.py
> +# Load the calibration data
```suggestion
# Load the calibration data.
```

2024-12-06 13:12 UTC, mcw92 commented on tutorials/alignment_optimization_tutorial.py
> +# Get optimizable parameters. (This will choose all 28 kinematic parameters)
```suggestion
# Get optimizable parameters. This will select all 28 kinematic parameters.
```

2024-12-06 13:12 UTC, mcw92 commented on tutorials/alignment_optimization_tutorial.py
> +# Set up optimizer and scheduler parameters
```suggestion
# Set up optimizer and scheduler parameters.
```

2024-12-06 13:13 UTC, mcw92 commented on tutorials/alignment_optimization_tutorial.py
> +# learning_rate_threshold = 0.1
I'd prefer no commented-out lines of code in the tutorial. Can we introduce a boolean flag for this?

2024-12-06 13:14 UTC, mcw92 commented on tutorials/alignment_optimization_tutorial.py
> +# Set up learning rate scheduler
```suggestion
# Set up learning rate scheduler.
```

2024-12-06 13:14 UTC, mcw92 commented on tutorials/alignment_optimization_tutorial.py
> +# Create alignment optimizer
```suggestion
# Create alignment optimizer.
```

2024-12-06 13:20 UTC, mcw92 requested changes
Thank you for your effort in putting together this code; it was obviously a lot of work.

We’ve provided comments at various points which should be addressed before merging. In addition, the main areas for improvement are as follows:
 1. Ensure that all raise blocks are covered by tests.
 2. Avoid code duplication where possible — there are several instances that would benefit from refactoring.
 3. Please ensure there are no hardcoded PAINT-specific strings in the dictionaries. This functionality should be handled through mapping.
 4. The surface converter could use refactoring. We’ve added multiple comments to guide you in this area.
 5. Finally, aim to include more unit tests. Currently, the tests seem predominantly integration-focused, and unit tests would improve coverage and reliability.

2024-12-06 14:19 UTC, MarleneBusch commented on artist/util/paint_to_surface_converter.py
> +    def fit_nurbs_surface(
done, i chose this: create a surface converter class with common attributes and have different methods defining the conversion to be performed.

2024-12-06 14:22 UTC, MarleneBusch commented on artist/util/paint_to_surface_converter.py
> +            The conversion method used to learn the NURBS.
done

2024-12-06 14:47 UTC, MarleneBusch commented on artist/util/paint_to_surface_converter.py
> +        Parameters
done

2024-12-06 14:47 UTC, MarleneBusch commented on artist/util/paint_to_surface_converter.py
> +        # How to deal with different amount of points on different facets?
done

2024-12-06 14:47 UTC, MarleneBusch commented on artist/util/paint_to_surface_converter.py
> +        # Select only selected number of points to reduce compute.
done

2024-12-06 14:48 UTC, MarleneBusch commented on artist/util/paint_to_surface_converter.py
> +        log.info("Surface configuration based on STRAL data complete!")
done

2024-12-06 14:48 UTC, MarleneBusch commented on artist/util/paint_to_surface_converter.py
> +            for f in range(number_of_facets):
done

2024-12-06 15:02 UTC, MarleneBusch commented on tests/data/scenario_generators/generate_scenario_for_test_alignment_optimizer.py
> +    plane_e = (
i put it into utils

2024-12-06 15:04 UTC, MarleneBusch commented on tests/util/test_alignment_optimizer_methods.py
> +    # Load the calibration data
done

2024-12-06 15:04 UTC, MarleneBusch commented on tests/util/test_alignment_optimizer_methods.py
> +    # Create alignment optimizer
done

2024-12-06 15:05 UTC, MarleneBusch commented on tests/util/test_wgs84_to_enu.py
> +        # Coordinates of Jülich power plant and multifocustower
done

2024-12-06 15:07 UTC, MarleneBusch commented on tests/util/test_wgs84_to_enu.py
> +    Test the WGS84 to enu conversion.
done

2024-12-06 15:07 UTC, MarleneBusch commented on tutorials/alignment_optimization_tutorial.py
> +# Set up logger
done

2024-12-06 15:07 UTC, MarleneBusch commented on tutorials/alignment_optimization_tutorial.py
> +# Set the device
done

2024-12-06 15:07 UTC, MarleneBusch commented on tutorials/alignment_optimization_tutorial.py
> +# Choose calibration data
done

2024-12-06 15:08 UTC, MarleneBusch commented on tutorials/alignment_optimization_tutorial.py
> +# Load the calibration data
done

2024-12-06 15:08 UTC, MarleneBusch commented on tutorials/alignment_optimization_tutorial.py
> +# Get optimizable parameters. (This will choose all 28 kinematic parameters)
done

2024-12-06 15:08 UTC, MarleneBusch commented on tutorials/alignment_optimization_tutorial.py
> +# Set up optimizer and scheduler parameters
done

2024-12-06 15:10 UTC, MarleneBusch commented on tutorials/alignment_optimization_tutorial.py
> +# Set up learning rate scheduler
done

2024-12-06 15:11 UTC, MarleneBusch commented on tutorials/alignment_optimization_tutorial.py
> +# Create alignment optimizer
done

2024-12-06 15:17 UTC, MarleneBusch commented on tests/util/test_wgs84_to_enu.py
> +@pytest.fixture(params=["cpu", "cuda"] if torch.cuda.is_available() else ["cpu"])
done

2024-12-09 07:41 UTC, MarleneBusch commented on artist/field/actuator_linear.py
> -    def forward(
yes, sorry, thats what i meant.
I implemented the forward methods like you suggested everywhere and afterwards i tested the code.
There are no errors in combination with the forward methods. I will open an issue.

2024-12-09 12:55 UTC, MarleneBusch commented on artist/util/alignment_optimizer.py
> +            if epoch in [max_epoch // 4, 2 * (max_epoch // 4), 3 * (max_epoch // 4)]:
done

2024-12-09 13:55 UTC, MarleneBusch commented on artist/util/paint_to_surface_converter.py
> +        with open(self.heliostat_file_path, "r") as file:
done

2024-12-10 14:33 UTC, MarleneBusch commented on tests/data/scenario_generators/generate_scenario_for_test_alignment_optimizer.py
> +    concentrator_translation_u=torch.tensor(-0.4045, device=device),
done

2024-12-10 14:33 UTC, MarleneBusch commented on tests/data/scenario_generators/generate_scenario_for_test_alignment_optimizer.py
> +)
done

2024-12-10 14:33 UTC, MarleneBusch commented on tests/field/test_kinematic_with_measured_parameters.py
> +    ].initial_angle = torch.tensor(0.959931, device=device)
done

2024-12-10 14:34 UTC, MarleneBusch commented on tests/field/test_kinematic_with_measured_parameters.py
> +    assert final_bitmap.sum() != 0
done

2024-12-10 14:34 UTC, MarleneBusch commented on tests/field/test_kinematic_with_measured_parameters.py
> +    Test the kinematic with measured parameters.
done

2024-12-11 10:52 UTC, MarleneBusch commented on artist/field/heliostat.py
> +                raise ValueError(
done

2024-12-11 10:52 UTC, MarleneBusch commented on artist/field/heliostat.py
> +                raise ValueError(
done

2024-12-11 10:53 UTC, MarleneBusch commented on artist/field/heliostat.py
> +                raise ValueError(
done

2024-12-11 11:20 UTC, MarleneBusch commented on artist/field/heliostat.py
> +            raise ValueError("Heliostat has not yet been aligned.")
done

2024-12-11 12:32 UTC, MarleneBusch commented on artist/field/kinematic_rigid_body.py
> +        # aligned_surface_normals = surface_normals @ orientation.T
done. 

transpose is quicker.

2024-12-11 12:32 UTC, MarleneBusch commented on artist/field/kinematic_rigid_body.py
> +        ).squeeze()
done. 

transpose is quicker.

2024-12-11 12:32 UTC, MarleneBusch commented on tests/data/scenario_generators/generate_scenario_for_test_alignment_optimizer.py
> +with open(calibration_file, "r") as file:
done

2024-12-11 15:26 UTC, MarleneBusch commented on tests/util/test_alignment_optimizer_methods.py
> +    if optimizer_method == "use_raytracing":
done

2024-12-12 14:47 UTC, MarleneBusch commented on tests/util/test_alignment_optimizer_methods.py
> +def test_alignment_optimizer_methods(
there is no other way to test the alignemnt optimizer methods.

2024-12-12 14:53 UTC, MarleneBusch commented
I added a lot of tests to cover all raise blocks.
I merged the stral and paint to surface converters into a single surface converter.
I removed all strings to read paint data and used mapping instead.

2024-12-13 10:04 UTC, kalebphipps requested changes
The number of changed files seems to keep exponentially growing! This is definitely a huge contribution!

Thanks for all the changes - especially all the tests to cover errors and the additional unit tests make a huge difference. I also like the way the `SurfaceConverter` is refactored.

I have included a few comments - most are minor points regarding DocStrings or things that we should maybe note as Issues to deal with later. I think the two important things are:
- A small suggestion to further refactor the `SurfaceConverter`.
- Some notes on files being included from test coverage. I know they were previously excluded, but looking through the code I think there might still be some things we can test there.

I also noticed that the updated keys for the ``PAINT`` data have not yet been included - we should probably update these (i.e. `sun_azimuth` instead of `Sun_azimuth`) and fix the test data before merging right? 

Locally (I will push now) I have formatted the test `.json` files to be "pretty" and also included a numbering for the alignment tutorial in the file name.

Thanks again for all the work - and sorry for the further requested changes...there are so many changes that I keep noticing new things when I review it again...

2024-12-13 10:45 UTC, MarleneBusch commented on artist/util/config_dictionary.py
> +paint_sun_azimuth = "Sun_azimuth"
done

2024-12-13 11:18 UTC, MarleneBusch commented on artist/raytracing/rays.py
> +            raise ValueError("Ray directions and magnitudes have differing sizes!")
done

2024-12-13 11:21 UTC, MarleneBusch commented on artist/util/surface_converter.py
> +        Generate a surface configuration from a ``STRAL`` file.
done

2024-12-13 11:22 UTC, MarleneBusch commented on artist/util/surface_converter.py
> +        Generate a surface configuration from a ``PAINT`` dataset.
done

2024-12-13 11:24 UTC, MarleneBusch commented on artist/util/utils.py
> +def normalize_points(points: torch.Tensor) -> torch.Tensor:
it is not being tested because its only used in the paint loader. This will be resolved once i write a test for the paint loader

2024-12-13 11:24 UTC, MarleneBusch commented on artist/util/utils.py
> +def corner_points_to_plane(
it is not being tested because its only used in the paint loader. This will be resolved once i write a test for the paint loader

2024-12-13 11:45 UTC, MarleneBusch commented on artist/util/surface_converter.py
> +    def generate_surface_config(
done

2024-12-13 11:48 UTC, MarleneBusch commented on tests/data/calibration_properties.json
As of now i dont think I can do that in VSCode this quick, so it would be nice if you keep doing that in the future.

2024-12-13 11:50 UTC, MarleneBusch commented on tests/field/test_set_preferred_reflection_direction.py
> +
done

2024-12-13 11:50 UTC, MarleneBusch commented on tests/scene/test_load_light_source_array.py
> +    Test the heliostat load from hdf5 method.
done

2024-12-13 11:56 UTC, MarleneBusch commented on tests/util/test_all_forward.py
i created another issue

2024-12-13 13:06 UTC, MarleneBusch commented on pyproject.toml
> +    "artist/util/surface_converter.py",
done

2024-12-13 14:09 UTC, MarleneBusch commented on pyproject.toml
> +    "artist/util/paint_loader.py",
done

2024-12-13 14:10 UTC, MarleneBusch commented on artist/util/utils.py
> +def normalize_points(points: torch.Tensor) -> torch.Tensor:
done

2024-12-13 14:10 UTC, MarleneBusch commented on artist/util/utils.py
> +def corner_points_to_plane(
done

2024-12-16 09:31 UTC, kalebphipps approved these changes
I have made a few changes to the docstrings and test coverage locally which I will now push.

It looks good to me though - I am happy to allow the merge!

2024-12-16 10:39 UTC, mcw92 approved these changes

2024-12-16 10:41 UTC, merged